# Use the oficial Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory 
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any Needed Packages specified in requirements.txt
RUN pip install flask

# Make port 5000 available to the world outside the container
EXPOSE 5000

# Run app.py when the container launches 
CMD [ "python", "app.py"]

